/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HandwritingCanvasRequestDto,
  HandwritingCanvasResponseDto,
} from '../models/index';
import {
    HandwritingCanvasRequestDtoFromJSON,
    HandwritingCanvasRequestDtoToJSON,
    HandwritingCanvasResponseDtoFromJSON,
    HandwritingCanvasResponseDtoToJSON,
} from '../models/index';

export interface ApiHandwritingOcrPostRequest {
    handwritingCanvasRequestDto?: HandwritingCanvasRequestDto;
}

/**
 * 
 */
export class HandwritingApi extends runtime.BaseAPI {

    /**
     */
    async apiHandwritingOcrPostRaw(requestParameters: ApiHandwritingOcrPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandwritingCanvasResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/handwriting/ocr`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HandwritingCanvasRequestDtoToJSON(requestParameters['handwritingCanvasRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandwritingCanvasResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiHandwritingOcrPost(requestParameters: ApiHandwritingOcrPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandwritingCanvasResponseDto> {
        const response = await this.apiHandwritingOcrPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
