/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HandwritingCanvasRequestDto,
  HandwritingCanvasResponseDto,
  LanguageCode,
  TranslatePhrasesResponseDto,
} from '../models/index';
import {
    HandwritingCanvasRequestDtoFromJSON,
    HandwritingCanvasRequestDtoToJSON,
    HandwritingCanvasResponseDtoFromJSON,
    HandwritingCanvasResponseDtoToJSON,
    LanguageCodeFromJSON,
    LanguageCodeToJSON,
    TranslatePhrasesResponseDtoFromJSON,
    TranslatePhrasesResponseDtoToJSON,
} from '../models/index';

export interface ApiHandwritingOcrPostRequest {
    handwritingCanvasRequestDto?: HandwritingCanvasRequestDto;
}

export interface ApiHandwritingOcrTranslateGetRequest {
    phrases?: Array<string>;
    languageCode?: LanguageCode;
    difficulty?: number;
}

/**
 * 
 */
export class HandwritingApi extends runtime.BaseAPI {

    /**
     */
    async apiHandwritingOcrPostRaw(requestParameters: ApiHandwritingOcrPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandwritingCanvasResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/handwriting/ocr`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HandwritingCanvasRequestDtoToJSON(requestParameters['handwritingCanvasRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandwritingCanvasResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiHandwritingOcrPost(requestParameters: ApiHandwritingOcrPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandwritingCanvasResponseDto> {
        const response = await this.apiHandwritingOcrPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiHandwritingOcrTranslateGetRaw(requestParameters: ApiHandwritingOcrTranslateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TranslatePhrasesResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['phrases'] != null) {
            queryParameters['Phrases'] = requestParameters['phrases'];
        }

        if (requestParameters['languageCode'] != null) {
            queryParameters['LanguageCode'] = requestParameters['languageCode'];
        }

        if (requestParameters['difficulty'] != null) {
            queryParameters['Difficulty'] = requestParameters['difficulty'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/handwriting/ocr/translate`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TranslatePhrasesResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiHandwritingOcrTranslateGet(requestParameters: ApiHandwritingOcrTranslateGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TranslatePhrasesResponseDto> {
        const response = await this.apiHandwritingOcrTranslateGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
