/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiQuizRomanizationPostRequest,
  ProblemDetails,
  QuizResponseDto,
} from '../models/index';
import {
    ApiQuizRomanizationPostRequestFromJSON,
    ApiQuizRomanizationPostRequestToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    QuizResponseDtoFromJSON,
    QuizResponseDtoToJSON,
} from '../models/index';

export interface ApiQuizAudioPostRequest {
    apiQuizRomanizationPostRequest?: ApiQuizRomanizationPostRequest;
}

export interface ApiQuizRomanizationPostOperationRequest {
    apiQuizRomanizationPostRequest?: ApiQuizRomanizationPostRequest;
}

/**
 * 
 */
export class QuizApi extends runtime.BaseAPI {

    /**
     */
    async apiQuizAudioPostRaw(requestParameters: ApiQuizAudioPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuizResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/quiz/audio`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiQuizRomanizationPostRequestToJSON(requestParameters['apiQuizRomanizationPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuizResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiQuizAudioPost(requestParameters: ApiQuizAudioPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuizResponseDto> {
        const response = await this.apiQuizAudioPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiQuizRomanizationPostRaw(requestParameters: ApiQuizRomanizationPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuizResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/quiz/romanization`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiQuizRomanizationPostRequestToJSON(requestParameters['apiQuizRomanizationPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuizResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiQuizRomanizationPost(requestParameters: ApiQuizRomanizationPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuizResponseDto> {
        const response = await this.apiQuizRomanizationPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
