name: .NET Web API CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: /home/runner/work/Chord-KTV/ChordKtv

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Change version if needed

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test --no-build --configuration Release --verbosity normal

  run-app:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Change version if needed

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --no-restore --configuration Release

      - name: Start Web API
        run: |
          dotnet run --no-build --configuration Release &
          sleep 5 # Give it time to start

      - name: Check If API Health is Ok
        run: curl --fail app:5259/api/health || exit 1
