name: Lint Frontend Code Base

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Change if needed
          cache: 'npm'
          cache-dependency-path: 'frontend/lyric-sync-app/package-lock.json'

      - name: Install Dependencies
        run: |
          cd frontend/lyric-sync-app
          npm ci

      - name: Run ESLint
        run: |
          cd frontend/lyric-sync-app
          npm run lint
