name: Enforce PR Template

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Description
        id: check-pr
        uses: actions/github-script@v7
        with:
          script: |
            const requiredFields = [
              "## 📋 Summary",
              "## 🔍 Related Issues",
            ];

            const prBody = context.payload.pull_request.body || "";
            const missingFields = requiredFields.filter(field => !prBody.includes(field));

            if (missingFields.length > 0) {
              core.setFailed(`🚨 PR is missing required sections:\n${missingFields.join("\n")}`);
            }

      - name: Request Changes If PR Template is Incomplete
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"
          MESSAGE="⚠️ This PR does not follow our contribution guidelines. Please complete all required sections before review."

          curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${REPO}/pulls/${PR_NUMBER}/reviews \
          -d '{"body": "'"${MESSAGE}"'", "event": "REQUEST_CHANGES"}'
