/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiQuizRomanizationPostRequest
 */
export interface ApiQuizRomanizationPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiQuizRomanizationPostRequest
     */
    songId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiQuizRomanizationPostRequest
     */
    useCachedQuiz?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ApiQuizRomanizationPostRequest
     */
    difficulty?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiQuizRomanizationPostRequest
     */
    numQuestions?: number;
}

/**
 * Check if a given object implements the ApiQuizRomanizationPostRequest interface.
 */
export function instanceOfApiQuizRomanizationPostRequest(value: object): value is ApiQuizRomanizationPostRequest {
    return true;
}

export function ApiQuizRomanizationPostRequestFromJSON(json: any): ApiQuizRomanizationPostRequest {
    return ApiQuizRomanizationPostRequestFromJSONTyped(json, false);
}

export function ApiQuizRomanizationPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiQuizRomanizationPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'songId': json['songId'] == null ? undefined : json['songId'],
        'useCachedQuiz': json['useCachedQuiz'] == null ? undefined : json['useCachedQuiz'],
        'difficulty': json['difficulty'] == null ? undefined : json['difficulty'],
        'numQuestions': json['numQuestions'] == null ? undefined : json['numQuestions'],
    };
}

export function ApiQuizRomanizationPostRequestToJSON(json: any): ApiQuizRomanizationPostRequest {
    return ApiQuizRomanizationPostRequestToJSONTyped(json, false);
}

export function ApiQuizRomanizationPostRequestToJSONTyped(value?: ApiQuizRomanizationPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'songId': value['songId'],
        'useCachedQuiz': value['useCachedQuiz'],
        'difficulty': value['difficulty'],
        'numQuestions': value['numQuestions'],
    };
}

