/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FullSongRequestDto
 */
export interface FullSongRequestDto {
    /**
     *
     * @type {string}
     * @memberof FullSongRequestDto
     */
    title?: string | null;
    /**
     *
     * @type {string}
     * @memberof FullSongRequestDto
     */
    artist?: string | null;
    /**
     *
     * @type {string}
     * @memberof FullSongRequestDto
     */
    album?: string | null;
    /**
     *
     * @type {string}
     * @memberof FullSongRequestDto
     */
    duration?: string | null;
    /**
     *
     * @type {string}
     * @memberof FullSongRequestDto
     */
    lyrics?: string | null;
    /**
     *
     * @type {string}
     * @memberof FullSongRequestDto
     */
    youTubeId?: string | null;
}

/**
 * Check if a given object implements the FullSongRequestDto interface.
 */
export function instanceOfFullSongRequestDto(value: object): value is FullSongRequestDto {
    return true;
}

export function FullSongRequestDtoFromJSON(json: any): FullSongRequestDto {
    return FullSongRequestDtoFromJSONTyped(json, false);
}

export function FullSongRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FullSongRequestDto {
    if (json == null) {
        return json;
    }
    return {

        'title': json['title'] == null ? undefined : json['title'],
        'artist': json['artist'] == null ? undefined : json['artist'],
        'album': json['album'] == null ? undefined : json['album'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'lyrics': json['lyrics'] == null ? undefined : json['lyrics'],
        'youTubeId': json['youTubeId'] == null ? undefined : json['youTubeId'],
    };
}

export function FullSongRequestDtoToJSON(json: any): FullSongRequestDto {
    return FullSongRequestDtoToJSONTyped(json, false);
}

export function FullSongRequestDtoToJSONTyped(value?: FullSongRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'title': value['title'],
        'artist': value['artist'],
        'album': value['album'],
        'duration': value['duration'],
        'lyrics': value['lyrics'],
        'youTubeId': value['youTubeId'],
    };
}

