/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageCode } from './LanguageCode';
import {
    LanguageCodeFromJSON,
    LanguageCodeFromJSONTyped,
    LanguageCodeToJSON,
    LanguageCodeToJSONTyped,
} from './LanguageCode';

/**
 * 
 * @export
 * @interface GeniusMetaData
 */
export interface GeniusMetaData {
    /**
     * 
     * @type {number}
     * @memberof GeniusMetaData
     */
    geniusId?: number;
    /**
     * 
     * @type {string}
     * @memberof GeniusMetaData
     */
    headerImageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeniusMetaData
     */
    headerImageThumbnailUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeniusMetaData
     */
    songImageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeniusMetaData
     */
    songImageThumbnailUrl?: string | null;
    /**
     * 
     * @type {LanguageCode}
     * @memberof GeniusMetaData
     */
    language?: LanguageCode;
}



/**
 * Check if a given object implements the GeniusMetaData interface.
 */
export function instanceOfGeniusMetaData(value: object): value is GeniusMetaData {
    return true;
}

export function GeniusMetaDataFromJSON(json: any): GeniusMetaData {
    return GeniusMetaDataFromJSONTyped(json, false);
}

export function GeniusMetaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeniusMetaData {
    if (json == null) {
        return json;
    }
    return {
        
        'geniusId': json['geniusId'] == null ? undefined : json['geniusId'],
        'headerImageUrl': json['headerImageUrl'] == null ? undefined : json['headerImageUrl'],
        'headerImageThumbnailUrl': json['headerImageThumbnailUrl'] == null ? undefined : json['headerImageThumbnailUrl'],
        'songImageUrl': json['songImageUrl'] == null ? undefined : json['songImageUrl'],
        'songImageThumbnailUrl': json['songImageThumbnailUrl'] == null ? undefined : json['songImageThumbnailUrl'],
        'language': json['language'] == null ? undefined : LanguageCodeFromJSON(json['language']),
    };
}

export function GeniusMetaDataToJSON(json: any): GeniusMetaData {
    return GeniusMetaDataToJSONTyped(json, false);
}

export function GeniusMetaDataToJSONTyped(value?: GeniusMetaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'geniusId': value['geniusId'],
        'headerImageUrl': value['headerImageUrl'],
        'headerImageThumbnailUrl': value['headerImageThumbnailUrl'],
        'songImageUrl': value['songImageUrl'],
        'songImageThumbnailUrl': value['songImageThumbnailUrl'],
        'language': LanguageCodeToJSON(value['language']),
    };
}

