/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeniusAlbum
 */
export interface GeniusAlbum {
    /**
     * 
     * @type {string}
     * @memberof GeniusAlbum
     */
    name?: string | null;
}

/**
 * Check if a given object implements the GeniusAlbum interface.
 */
export function instanceOfGeniusAlbum(value: object): value is GeniusAlbum {
    return true;
}

export function GeniusAlbumFromJSON(json: any): GeniusAlbum {
    return GeniusAlbumFromJSONTyped(json, false);
}

export function GeniusAlbumFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeniusAlbum {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GeniusAlbumToJSON(json: any): GeniusAlbum {
    return GeniusAlbumToJSONTyped(json, false);
}

export function GeniusAlbumToJSONTyped(value?: GeniusAlbum | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

