/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeniusAlbum } from './GeniusAlbum';
import {
    GeniusAlbumFromJSON,
    GeniusAlbumFromJSONTyped,
    GeniusAlbumToJSON,
    GeniusAlbumToJSONTyped,
} from './GeniusAlbum';

/**
 * 
 * @export
 * @interface GeniusResult
 */
export interface GeniusResult {
    /**
     * 
     * @type {number}
     * @memberof GeniusResult
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GeniusResult
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeniusResult
     */
    headerImageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeniusResult
     */
    songArtImageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeniusResult
     */
    primaryArtistNames?: string | null;
    /**
     * 
     * @type {GeniusAlbum}
     * @memberof GeniusResult
     */
    album?: GeniusAlbum;
}

/**
 * Check if a given object implements the GeniusResult interface.
 */
export function instanceOfGeniusResult(value: object): value is GeniusResult {
    return true;
}

export function GeniusResultFromJSON(json: any): GeniusResult {
    return GeniusResultFromJSONTyped(json, false);
}

export function GeniusResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeniusResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'headerImageUrl': json['header_image_url'] == null ? undefined : json['header_image_url'],
        'songArtImageUrl': json['song_art_image_url'] == null ? undefined : json['song_art_image_url'],
        'primaryArtistNames': json['primary_artist_names'] == null ? undefined : json['primary_artist_names'],
        'album': json['album'] == null ? undefined : GeniusAlbumFromJSON(json['album']),
    };
}

export function GeniusResultToJSON(json: any): GeniusResult {
    return GeniusResultToJSONTyped(json, false);
}

export function GeniusResultToJSONTyped(value?: GeniusResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'header_image_url': value['headerImageUrl'],
        'song_art_image_url': value['songArtImageUrl'],
        'primary_artist_names': value['primaryArtistNames'],
        'album': GeniusAlbumToJSON(value['album']),
    };
}

