/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageCode } from './LanguageCode';
import {
    LanguageCodeFromJSON,
    LanguageCodeFromJSONTyped,
    LanguageCodeToJSON,
    LanguageCodeToJSONTyped,
} from './LanguageCode';

/**
 * 
 * @export
 * @interface GeniusMetaDataDto
 */
export interface GeniusMetaDataDto {
    /**
     * 
     * @type {number}
     * @memberof GeniusMetaDataDto
     */
    geniusId?: number;
    /**
     * 
     * @type {string}
     * @memberof GeniusMetaDataDto
     */
    headerImageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeniusMetaDataDto
     */
    songImageUrl?: string | null;
    /**
     * 
     * @type {LanguageCode}
     * @memberof GeniusMetaDataDto
     */
    language?: LanguageCode;
}



/**
 * Check if a given object implements the GeniusMetaDataDto interface.
 */
export function instanceOfGeniusMetaDataDto(value: object): value is GeniusMetaDataDto {
    return true;
}

export function GeniusMetaDataDtoFromJSON(json: any): GeniusMetaDataDto {
    return GeniusMetaDataDtoFromJSONTyped(json, false);
}

export function GeniusMetaDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeniusMetaDataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'geniusId': json['geniusId'] == null ? undefined : json['geniusId'],
        'headerImageUrl': json['headerImageUrl'] == null ? undefined : json['headerImageUrl'],
        'songImageUrl': json['songImageUrl'] == null ? undefined : json['songImageUrl'],
        'language': json['language'] == null ? undefined : LanguageCodeFromJSON(json['language']),
    };
}

export function GeniusMetaDataDtoToJSON(json: any): GeniusMetaDataDto {
    return GeniusMetaDataDtoToJSONTyped(json, false);
}

export function GeniusMetaDataDtoToJSONTyped(value?: GeniusMetaDataDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'geniusId': value['geniusId'],
        'headerImageUrl': value['headerImageUrl'],
        'songImageUrl': value['songImageUrl'],
        'language': LanguageCodeToJSON(value['language']),
    };
}

