/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeniusResult } from './GeniusResult';
import {
    GeniusResultFromJSON,
    GeniusResultFromJSONTyped,
    GeniusResultToJSON,
    GeniusResultToJSONTyped,
} from './GeniusResult';

/**
 * 
 * @export
 * @interface GeniusHit
 */
export interface GeniusHit {
    /**
     * 
     * @type {GeniusResult}
     * @memberof GeniusHit
     */
    result?: GeniusResult;
}

/**
 * Check if a given object implements the GeniusHit interface.
 */
export function instanceOfGeniusHit(value: object): value is GeniusHit {
    return true;
}

export function GeniusHitFromJSON(json: any): GeniusHit {
    return GeniusHitFromJSONTyped(json, false);
}

export function GeniusHitFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeniusHit {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : GeniusResultFromJSON(json['result']),
    };
}

export function GeniusHitToJSON(json: any): GeniusHit {
    return GeniusHitToJSONTyped(json, false);
}

export function GeniusHitToJSONTyped(value?: GeniusHit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': GeniusResultToJSON(value['result']),
    };
}

