/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeniusAlbumDto
 */
export interface GeniusAlbumDto {
    /**
     * 
     * @type {string}
     * @memberof GeniusAlbumDto
     */
    name: string;
}

/**
 * Check if a given object implements the GeniusAlbumDto interface.
 */
export function instanceOfGeniusAlbumDto(value: object): value is GeniusAlbumDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GeniusAlbumDtoFromJSON(json: any): GeniusAlbumDto {
    return GeniusAlbumDtoFromJSONTyped(json, false);
}

export function GeniusAlbumDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeniusAlbumDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function GeniusAlbumDtoToJSON(json: any): GeniusAlbumDto {
    return GeniusAlbumDtoToJSONTyped(json, false);
}

export function GeniusAlbumDtoToJSONTyped(value?: GeniusAlbumDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

