/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandwritingCanvasResponseDto
 */
export interface HandwritingCanvasResponseDto {
    /**
     * 
     * @type {string}
     * @memberof HandwritingCanvasResponseDto
     */
    recognizedText?: string | null;
    /**
     * 
     * @type {number}
     * @memberof HandwritingCanvasResponseDto
     */
    matchPercentage?: number;
}

/**
 * Check if a given object implements the HandwritingCanvasResponseDto interface.
 */
export function instanceOfHandwritingCanvasResponseDto(value: object): value is HandwritingCanvasResponseDto {
    return true;
}

export function HandwritingCanvasResponseDtoFromJSON(json: any): HandwritingCanvasResponseDto {
    return HandwritingCanvasResponseDtoFromJSONTyped(json, false);
}

export function HandwritingCanvasResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandwritingCanvasResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'recognizedText': json['recognizedText'] == null ? undefined : json['recognizedText'],
        'matchPercentage': json['matchPercentage'] == null ? undefined : json['matchPercentage'],
    };
}

export function HandwritingCanvasResponseDtoToJSON(json: any): HandwritingCanvasResponseDto {
    return HandwritingCanvasResponseDtoToJSONTyped(json, false);
}

export function HandwritingCanvasResponseDtoToJSONTyped(value?: HandwritingCanvasResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recognizedText': value['recognizedText'],
        'matchPercentage': value['matchPercentage'],
    };
}

