/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageCode } from './LanguageCode';
import {
    LanguageCodeFromJSON,
    LanguageCodeFromJSONTyped,
    LanguageCodeToJSON,
    LanguageCodeToJSONTyped,
} from './LanguageCode';

/**
 * 
 * @export
 * @interface HandwritingCanvasDto
 */
export interface HandwritingCanvasDto {
    /**
     * 
     * @type {string}
     * @memberof HandwritingCanvasDto
     */
    image?: string | null;
    /**
     * 
     * @type {LanguageCode}
     * @memberof HandwritingCanvasDto
     */
    language?: LanguageCode;
    /**
     * 
     * @type {string}
     * @memberof HandwritingCanvasDto
     */
    expectedMatch?: string | null;
}



/**
 * Check if a given object implements the HandwritingCanvasDto interface.
 */
export function instanceOfHandwritingCanvasDto(value: object): value is HandwritingCanvasDto {
    return true;
}

export function HandwritingCanvasDtoFromJSON(json: any): HandwritingCanvasDto {
    return HandwritingCanvasDtoFromJSONTyped(json, false);
}

export function HandwritingCanvasDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandwritingCanvasDto {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'] == null ? undefined : json['image'],
        'language': json['language'] == null ? undefined : LanguageCodeFromJSON(json['language']),
        'expectedMatch': json['expectedMatch'] == null ? undefined : json['expectedMatch'],
    };
}

export function HandwritingCanvasDtoToJSON(json: any): HandwritingCanvasDto {
    return HandwritingCanvasDtoToJSONTyped(json, false);
}

export function HandwritingCanvasDtoToJSONTyped(value?: HandwritingCanvasDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
        'language': LanguageCodeToJSON(value['language']),
        'expectedMatch': value['expectedMatch'],
    };
}

