/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LanguageCode = {
    Unk: 'UNK',
    Af: 'AF',
    Ar: 'AR',
    Bg: 'BG',
    Bn: 'BN',
    Ca: 'CA',
    Cs: 'CS',
    Da: 'DA',
    De: 'DE',
    El: 'EL',
    En: 'EN',
    Es: 'ES',
    Et: 'ET',
    Fa: 'FA',
    Fi: 'FI',
    Fr: 'FR',
    Gu: 'GU',
    He: 'HE',
    Hi: 'HI',
    Hr: 'HR',
    Hu: 'HU',
    Id: 'ID',
    It: 'IT',
    Ja: 'JA',
    Ko: 'KO',
    Lt: 'LT',
    Lv: 'LV',
    Ms: 'MS',
    Nl: 'NL',
    No: 'NO',
    Pl: 'PL',
    Pt: 'PT',
    Ro: 'RO',
    Ru: 'RU',
    Sk: 'SK',
    Sl: 'SL',
    Sr: 'SR',
    Sv: 'SV',
    Ta: 'TA',
    Te: 'TE',
    Th: 'TH',
    Tr: 'TR',
    Uk: 'UK',
    Vi: 'VI',
    Zh: 'ZH'
} as const;
export type LanguageCode = typeof LanguageCode[keyof typeof LanguageCode];


export function instanceOfLanguageCode(value: any): boolean {
    for (const key in LanguageCode) {
        if (Object.prototype.hasOwnProperty.call(LanguageCode, key)) {
            if (LanguageCode[key as keyof typeof LanguageCode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LanguageCodeFromJSON(json: any): LanguageCode {
    return LanguageCodeFromJSONTyped(json, false);
}

export function LanguageCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguageCode {
    return json as LanguageCode;
}

export function LanguageCodeToJSON(value?: LanguageCode | null): any {
    return value as any;
}

export function LanguageCodeToJSONTyped(value: any, ignoreDiscriminator: boolean): LanguageCode {
    return value as LanguageCode;
}

