/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageCode } from './LanguageCode';
import {
    LanguageCodeFromJSON,
    LanguageCodeFromJSONTyped,
    LanguageCodeToJSON,
    LanguageCodeToJSONTyped,
} from './LanguageCode';

/**
 * 
 * @export
 * @interface LearnedWordDto
 */
export interface LearnedWordDto {
    /**
     * 
     * @type {string}
     * @memberof LearnedWordDto
     */
    word?: string;
    /**
     * 
     * @type {LanguageCode}
     * @memberof LearnedWordDto
     */
    language?: LanguageCode;
    /**
     * 
     * @type {Date}
     * @memberof LearnedWordDto
     */
    dateLearned?: Date | null;
}



/**
 * Check if a given object implements the LearnedWordDto interface.
 */
export function instanceOfLearnedWordDto(value: object): value is LearnedWordDto {
    return true;
}

export function LearnedWordDtoFromJSON(json: any): LearnedWordDto {
    return LearnedWordDtoFromJSONTyped(json, false);
}

export function LearnedWordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearnedWordDto {
    if (json == null) {
        return json;
    }
    return {
        
        'word': json['word'] == null ? undefined : json['word'],
        'language': json['language'] == null ? undefined : LanguageCodeFromJSON(json['language']),
        'dateLearned': json['dateLearned'] == null ? undefined : (new Date(json['dateLearned'])),
    };
}

export function LearnedWordDtoToJSON(json: any): LearnedWordDto {
    return LearnedWordDtoToJSONTyped(json, false);
}

export function LearnedWordDtoToJSONTyped(value?: LearnedWordDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'word': value['word'],
        'language': LanguageCodeToJSON(value['language']),
        'dateLearned': value['dateLearned'] == null ? undefined : ((value['dateLearned'] as any).toISOString()),
    };
}

