/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageCode } from './LanguageCode';
import {
    LanguageCodeFromJSON,
    LanguageCodeFromJSONTyped,
    LanguageCodeToJSON,
    LanguageCodeToJSONTyped,
} from './LanguageCode';

/**
 * 
 * @export
 * @interface LearnedWord
 */
export interface LearnedWord {
    /**
     * 
     * @type {string}
     * @memberof LearnedWord
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LearnedWord
     */
    word: string | null;
    /**
     * 
     * @type {LanguageCode}
     * @memberof LearnedWord
     */
    language?: LanguageCode;
    /**
     * 
     * @type {Date}
     * @memberof LearnedWord
     */
    dateLearned?: Date;
    /**
     * 
     * @type {string}
     * @memberof LearnedWord
     */
    userId?: string;
}



/**
 * Check if a given object implements the LearnedWord interface.
 */
export function instanceOfLearnedWord(value: object): value is LearnedWord {
    if (!('word' in value) || value['word'] === undefined) return false;
    return true;
}

export function LearnedWordFromJSON(json: any): LearnedWord {
    return LearnedWordFromJSONTyped(json, false);
}

export function LearnedWordFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearnedWord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'word': json['word'],
        'language': json['language'] == null ? undefined : LanguageCodeFromJSON(json['language']),
        'dateLearned': json['dateLearned'] == null ? undefined : (new Date(json['dateLearned'])),
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function LearnedWordToJSON(json: any): LearnedWord {
    return LearnedWordToJSONTyped(json, false);
}

export function LearnedWordToJSONTyped(value?: LearnedWord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'word': value['word'],
        'language': LanguageCodeToJSON(value['language']),
        'dateLearned': value['dateLearned'] == null ? undefined : ((value['dateLearned']).toISOString()),
        'userId': value['userId'],
    };
}

