/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatchScores
 */
export interface MatchScores {
    /**
     * 
     * @type {boolean}
     * @memberof MatchScores
     */
    lrcExactMatch?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MatchScores
     */
    lrcRomanizedScore?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MatchScores
     */
    lrcOriginalScore?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MatchScores
     */
    lrcInputParamScore?: number | null;
}

/**
 * Check if a given object implements the MatchScores interface.
 */
export function instanceOfMatchScores(value: object): value is MatchScores {
    return true;
}

export function MatchScoresFromJSON(json: any): MatchScores {
    return MatchScoresFromJSONTyped(json, false);
}

export function MatchScoresFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchScores {
    if (json == null) {
        return json;
    }
    return {
        
        'lrcExactMatch': json['lrcExactMatch'] == null ? undefined : json['lrcExactMatch'],
        'lrcRomanizedScore': json['lrcRomanizedScore'] == null ? undefined : json['lrcRomanizedScore'],
        'lrcOriginalScore': json['lrcOriginalScore'] == null ? undefined : json['lrcOriginalScore'],
        'lrcInputParamScore': json['lrcInputParamScore'] == null ? undefined : json['lrcInputParamScore'],
    };
}

export function MatchScoresToJSON(json: any): MatchScores {
    return MatchScoresToJSONTyped(json, false);
}

export function MatchScoresToJSONTyped(value?: MatchScores | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lrcExactMatch': value['lrcExactMatch'],
        'lrcRomanizedScore': value['lrcRomanizedScore'],
        'lrcOriginalScore': value['lrcOriginalScore'],
        'lrcInputParamScore': value['lrcInputParamScore'],
    };
}

