/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Phrases
 */
export interface Phrases {
    /**
     * 
     * @type {string}
     * @memberof Phrases
     */
    original?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Phrases
     */
    romanized?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Phrases
     */
    translated?: string | null;
}

/**
 * Check if a given object implements the Phrases interface.
 */
export function instanceOfPhrases(value: object): value is Phrases {
    return true;
}

export function PhrasesFromJSON(json: any): Phrases {
    return PhrasesFromJSONTyped(json, false);
}

export function PhrasesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Phrases {
    if (json == null) {
        return json;
    }
    return {
        
        'original': json['original'] == null ? undefined : json['original'],
        'romanized': json['romanized'] == null ? undefined : json['romanized'],
        'translated': json['translated'] == null ? undefined : json['translated'],
    };
}

export function PhrasesToJSON(json: any): Phrases {
    return PhrasesToJSONTyped(json, false);
}

export function PhrasesToJSONTyped(value?: Phrases | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'original': value['original'],
        'romanized': value['romanized'],
        'translated': value['translated'],
    };
}

