/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuizQuestionDto
 */
export interface QuizQuestionDto {
    /**
     * 
     * @type {number}
     * @memberof QuizQuestionDto
     */
    questionNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof QuizQuestionDto
     */
    lyricPhrase?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof QuizQuestionDto
     */
    options?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof QuizQuestionDto
     */
    correctOptionIndex?: number | null;
}

/**
 * Check if a given object implements the QuizQuestionDto interface.
 */
export function instanceOfQuizQuestionDto(value: object): value is QuizQuestionDto {
    return true;
}

export function QuizQuestionDtoFromJSON(json: any): QuizQuestionDto {
    return QuizQuestionDtoFromJSONTyped(json, false);
}

export function QuizQuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuizQuestionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'questionNumber': json['questionNumber'] == null ? undefined : json['questionNumber'],
        'lyricPhrase': json['lyricPhrase'] == null ? undefined : json['lyricPhrase'],
        'options': json['options'] == null ? undefined : json['options'],
        'correctOptionIndex': json['correctOptionIndex'] == null ? undefined : json['correctOptionIndex'],
    };
}

export function QuizQuestionDtoToJSON(json: any): QuizQuestionDto {
    return QuizQuestionDtoToJSONTyped(json, false);
}

export function QuizQuestionDtoToJSONTyped(value?: QuizQuestionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'questionNumber': value['questionNumber'],
        'lyricPhrase': value['lyricPhrase'],
        'options': value['options'],
        'correctOptionIndex': value['correctOptionIndex'],
    };
}

