/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuizRequestDto
 */
export interface QuizRequestDto {
    /**
     * 
     * @type {string}
     * @memberof QuizRequestDto
     */
    songId: string;
    /**
     * 
     * @type {boolean}
     * @memberof QuizRequestDto
     */
    useCachedQuiz?: boolean;
    /**
     * 
     * @type {number}
     * @memberof QuizRequestDto
     */
    difficulty?: number;
    /**
     * 
     * @type {number}
     * @memberof QuizRequestDto
     */
    numQuestions?: number;
}

/**
 * Check if a given object implements the QuizRequestDto interface.
 */
export function instanceOfQuizRequestDto(value: object): value is QuizRequestDto {
    if (!('songId' in value) || value['songId'] === undefined) return false;
    return true;
}

export function QuizRequestDtoFromJSON(json: any): QuizRequestDto {
    return QuizRequestDtoFromJSONTyped(json, false);
}

export function QuizRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuizRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'songId': json['songId'],
        'useCachedQuiz': json['useCachedQuiz'] == null ? undefined : json['useCachedQuiz'],
        'difficulty': json['difficulty'] == null ? undefined : json['difficulty'],
        'numQuestions': json['numQuestions'] == null ? undefined : json['numQuestions'],
    };
}

export function QuizRequestDtoToJSON(json: any): QuizRequestDto {
    return QuizRequestDtoToJSONTyped(json, false);
}

export function QuizRequestDtoToJSONTyped(value?: QuizRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'songId': value['songId'],
        'useCachedQuiz': value['useCachedQuiz'],
        'difficulty': value['difficulty'],
        'numQuestions': value['numQuestions'],
    };
}

