/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuizQuestion } from './QuizQuestion';
import {
    QuizQuestionFromJSON,
    QuizQuestionFromJSONTyped,
    QuizQuestionToJSON,
    QuizQuestionToJSONTyped,
} from './QuizQuestion';

/**
 * 
 * @export
 * @interface QuizOption
 */
export interface QuizOption {
    /**
     * 
     * @type {string}
     * @memberof QuizOption
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof QuizOption
     */
    questionId?: string;
    /**
     * 
     * @type {QuizQuestion}
     * @memberof QuizOption
     */
    question?: QuizQuestion;
    /**
     * 
     * @type {string}
     * @memberof QuizOption
     */
    text?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof QuizOption
     */
    isCorrect?: boolean;
    /**
     * 
     * @type {number}
     * @memberof QuizOption
     */
    orderIndex?: number;
}

/**
 * Check if a given object implements the QuizOption interface.
 */
export function instanceOfQuizOption(value: object): value is QuizOption {
    return true;
}

export function QuizOptionFromJSON(json: any): QuizOption {
    return QuizOptionFromJSONTyped(json, false);
}

export function QuizOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuizOption {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'questionId': json['questionId'] == null ? undefined : json['questionId'],
        'question': json['question'] == null ? undefined : QuizQuestionFromJSON(json['question']),
        'text': json['text'] == null ? undefined : json['text'],
        'isCorrect': json['isCorrect'] == null ? undefined : json['isCorrect'],
        'orderIndex': json['orderIndex'] == null ? undefined : json['orderIndex'],
    };
}

export function QuizOptionToJSON(json: any): QuizOption {
    return QuizOptionToJSONTyped(json, false);
}

export function QuizOptionToJSONTyped(value?: QuizOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'questionId': value['questionId'],
        'question': QuizQuestionToJSON(value['question']),
        'text': value['text'],
        'isCorrect': value['isCorrect'],
        'orderIndex': value['orderIndex'],
    };
}

