/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPlaylistActivityDto
 */
export interface UserPlaylistActivityDto {
    /**
     * 
     * @type {string}
     * @memberof UserPlaylistActivityDto
     */
    playlistUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserPlaylistActivityDto
     */
    isFavorite?: boolean;
    /**
     * 
     * @type {Array<Date>}
     * @memberof UserPlaylistActivityDto
     */
    datesPlayed?: Array<Date> | null;
    /**
     * 
     * @type {Date}
     * @memberof UserPlaylistActivityDto
     */
    lastPlayed?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserPlaylistActivityDto
     */
    dateFavorited?: Date | null;
}

/**
 * Check if a given object implements the UserPlaylistActivityDto interface.
 */
export function instanceOfUserPlaylistActivityDto(value: object): value is UserPlaylistActivityDto {
    return true;
}

export function UserPlaylistActivityDtoFromJSON(json: any): UserPlaylistActivityDto {
    return UserPlaylistActivityDtoFromJSONTyped(json, false);
}

export function UserPlaylistActivityDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPlaylistActivityDto {
    if (json == null) {
        return json;
    }
    return {
        
        'playlistUrl': json['playlistUrl'] == null ? undefined : json['playlistUrl'],
        'isFavorite': json['isFavorite'] == null ? undefined : json['isFavorite'],
        'datesPlayed': json['datesPlayed'] == null ? undefined : json['datesPlayed'],
        'lastPlayed': json['lastPlayed'] == null ? undefined : (new Date(json['lastPlayed'])),
        'dateFavorited': json['dateFavorited'] == null ? undefined : (new Date(json['dateFavorited'])),
    };
}

export function UserPlaylistActivityDtoToJSON(json: any): UserPlaylistActivityDto {
    return UserPlaylistActivityDtoToJSONTyped(json, false);
}

export function UserPlaylistActivityDtoToJSONTyped(value?: UserPlaylistActivityDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playlistUrl': value['playlistUrl'],
        'isFavorite': value['isFavorite'],
        'datesPlayed': value['datesPlayed'],
        'lastPlayed': value['lastPlayed'] == null ? undefined : ((value['lastPlayed']).toISOString()),
        'dateFavorited': value['dateFavorited'] == null ? undefined : ((value['dateFavorited'] as any).toISOString()),
    };
}

