/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageCode } from './LanguageCode';
import {
    LanguageCodeFromJSON,
    LanguageCodeFromJSONTyped,
    LanguageCodeToJSON,
    LanguageCodeToJSONTyped,
} from './LanguageCode';

/**
 * 
 * @export
 * @interface UserQuizResultDto
 */
export interface UserQuizResultDto {
    /**
     * 
     * @type {string}
     * @memberof UserQuizResultDto
     */
    quizId?: string;
    /**
     * 
     * @type {number}
     * @memberof UserQuizResultDto
     */
    score?: number;
    /**
     * 
     * @type {LanguageCode}
     * @memberof UserQuizResultDto
     */
    language?: LanguageCode;
    /**
     * 
     * @type {Date}
     * @memberof UserQuizResultDto
     */
    dateCompleted?: Date | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserQuizResultDto
     */
    correctAnswers?: Array<string> | null;
}



/**
 * Check if a given object implements the UserQuizResultDto interface.
 */
export function instanceOfUserQuizResultDto(value: object): value is UserQuizResultDto {
    return true;
}

export function UserQuizResultDtoFromJSON(json: any): UserQuizResultDto {
    return UserQuizResultDtoFromJSONTyped(json, false);
}

export function UserQuizResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserQuizResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'quizId': json['quizId'] == null ? undefined : json['quizId'],
        'score': json['score'] == null ? undefined : json['score'],
        'language': json['language'] == null ? undefined : LanguageCodeFromJSON(json['language']),
        'dateCompleted': json['dateCompleted'] == null ? undefined : (new Date(json['dateCompleted'])),
        'correctAnswers': json['correctAnswers'] == null ? undefined : json['correctAnswers'],
    };
}

export function UserQuizResultDtoToJSON(json: any): UserQuizResultDto {
    return UserQuizResultDtoToJSONTyped(json, false);
}

export function UserQuizResultDtoToJSONTyped(value?: UserQuizResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quizId': value['quizId'],
        'score': value['score'],
        'language': LanguageCodeToJSON(value['language']),
        'dateCompleted': value['dateCompleted'] == null ? undefined : ((value['dateCompleted'] as any).toISOString()),
        'correctAnswers': value['correctAnswers'],
    };
}

