/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Song } from './Song';
import {
    SongFromJSON,
    SongFromJSONTyped,
    SongToJSON,
    SongToJSONTyped,
} from './Song';

/**
 * 
 * @export
 * @interface UserSongActivity
 */
export interface UserSongActivity {
    /**
     * 
     * @type {string}
     * @memberof UserSongActivity
     */
    id?: string;
    /**
     * 
     * @type {Song}
     * @memberof UserSongActivity
     */
    song: Song;
    /**
     * 
     * @type {string}
     * @memberof UserSongActivity
     */
    userId?: string;
    /**
     * 
     * @type {Array<Date>}
     * @memberof UserSongActivity
     */
    datesPlayed?: Array<Date> | null;
    /**
     * 
     * @type {Date}
     * @memberof UserSongActivity
     */
    lastPlayed?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof UserSongActivity
     */
    isFavorite?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UserSongActivity
     */
    dateFavorited?: Date | null;
}

/**
 * Check if a given object implements the UserSongActivity interface.
 */
export function instanceOfUserSongActivity(value: object): value is UserSongActivity {
    if (!('song' in value) || value['song'] === undefined) return false;
    return true;
}

export function UserSongActivityFromJSON(json: any): UserSongActivity {
    return UserSongActivityFromJSONTyped(json, false);
}

export function UserSongActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSongActivity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'song': SongFromJSON(json['song']),
        'userId': json['userId'] == null ? undefined : json['userId'],
        'datesPlayed': json['datesPlayed'] == null ? undefined : json['datesPlayed'],
        'lastPlayed': json['lastPlayed'] == null ? undefined : (new Date(json['lastPlayed'])),
        'isFavorite': json['isFavorite'] == null ? undefined : json['isFavorite'],
        'dateFavorited': json['dateFavorited'] == null ? undefined : (new Date(json['dateFavorited'])),
    };
}

export function UserSongActivityToJSON(json: any): UserSongActivity {
    return UserSongActivityToJSONTyped(json, false);
}

export function UserSongActivityToJSONTyped(value?: UserSongActivity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'song': SongToJSON(value['song']),
        'userId': value['userId'],
        'datesPlayed': value['datesPlayed'],
        'lastPlayed': value['lastPlayed'] == null ? undefined : ((value['lastPlayed']).toISOString()),
        'isFavorite': value['isFavorite'],
        'dateFavorited': value['dateFavorited'] == null ? undefined : ((value['dateFavorited'] as any).toISOString()),
    };
}

