/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSongActivityFavoriteRequestDto
 */
export interface UserSongActivityFavoriteRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UserSongActivityFavoriteRequestDto
     */
    songId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserSongActivityFavoriteRequestDto
     */
    isFavorite?: boolean;
}

/**
 * Check if a given object implements the UserSongActivityFavoriteRequestDto interface.
 */
export function instanceOfUserSongActivityFavoriteRequestDto(value: object): value is UserSongActivityFavoriteRequestDto {
    return true;
}

export function UserSongActivityFavoriteRequestDtoFromJSON(json: any): UserSongActivityFavoriteRequestDto {
    return UserSongActivityFavoriteRequestDtoFromJSONTyped(json, false);
}

export function UserSongActivityFavoriteRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSongActivityFavoriteRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'songId': json['songId'] == null ? undefined : json['songId'],
        'isFavorite': json['isFavorite'] == null ? undefined : json['isFavorite'],
    };
}

export function UserSongActivityFavoriteRequestDtoToJSON(json: any): UserSongActivityFavoriteRequestDto {
    return UserSongActivityFavoriteRequestDtoToJSONTyped(json, false);
}

export function UserSongActivityFavoriteRequestDtoToJSONTyped(value?: UserSongActivityFavoriteRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'songId': value['songId'],
        'isFavorite': value['isFavorite'],
    };
}

