/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageCode } from './LanguageCode';
import {
    LanguageCodeFromJSON,
    LanguageCodeFromJSONTyped,
    LanguageCodeToJSON,
    LanguageCodeToJSONTyped,
} from './LanguageCode';

/**
 * 
 * @export
 * @interface UserHandwritingResult
 */
export interface UserHandwritingResult {
    /**
     * 
     * @type {string}
     * @memberof UserHandwritingResult
     */
    id?: string;
    /**
     * 
     * @type {LanguageCode}
     * @memberof UserHandwritingResult
     */
    language?: LanguageCode;
    /**
     * 
     * @type {number}
     * @memberof UserHandwritingResult
     */
    score?: number;
    /**
     * 
     * @type {string}
     * @memberof UserHandwritingResult
     */
    wordTested?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserHandwritingResult
     */
    dateCompleted?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserHandwritingResult
     */
    userId?: string;
}



/**
 * Check if a given object implements the UserHandwritingResult interface.
 */
export function instanceOfUserHandwritingResult(value: object): value is UserHandwritingResult {
    return true;
}

export function UserHandwritingResultFromJSON(json: any): UserHandwritingResult {
    return UserHandwritingResultFromJSONTyped(json, false);
}

export function UserHandwritingResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserHandwritingResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'language': json['language'] == null ? undefined : LanguageCodeFromJSON(json['language']),
        'score': json['score'] == null ? undefined : json['score'],
        'wordTested': json['wordTested'] == null ? undefined : json['wordTested'],
        'dateCompleted': json['dateCompleted'] == null ? undefined : (new Date(json['dateCompleted'])),
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function UserHandwritingResultToJSON(json: any): UserHandwritingResult {
    return UserHandwritingResultToJSONTyped(json, false);
}

export function UserHandwritingResultToJSONTyped(value?: UserHandwritingResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'language': LanguageCodeToJSON(value['language']),
        'score': value['score'],
        'wordTested': value['wordTested'],
        'dateCompleted': value['dateCompleted'] == null ? undefined : ((value['dateCompleted']).toISOString()),
        'userId': value['userId'],
    };
}

