/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPlaylistActivityFavoriteRequestDto
 */
export interface UserPlaylistActivityFavoriteRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UserPlaylistActivityFavoriteRequestDto
     */
    playlistId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserPlaylistActivityFavoriteRequestDto
     */
    isFavorite?: boolean;
}

/**
 * Check if a given object implements the UserPlaylistActivityFavoriteRequestDto interface.
 */
export function instanceOfUserPlaylistActivityFavoriteRequestDto(value: object): value is UserPlaylistActivityFavoriteRequestDto {
    return true;
}

export function UserPlaylistActivityFavoriteRequestDtoFromJSON(json: any): UserPlaylistActivityFavoriteRequestDto {
    return UserPlaylistActivityFavoriteRequestDtoFromJSONTyped(json, false);
}

export function UserPlaylistActivityFavoriteRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPlaylistActivityFavoriteRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'playlistId': json['playlistId'] == null ? undefined : json['playlistId'],
        'isFavorite': json['isFavorite'] == null ? undefined : json['isFavorite'],
    };
}

export function UserPlaylistActivityFavoriteRequestDtoToJSON(json: any): UserPlaylistActivityFavoriteRequestDto {
    return UserPlaylistActivityFavoriteRequestDtoToJSONTyped(json, false);
}

export function UserPlaylistActivityFavoriteRequestDtoToJSONTyped(value?: UserPlaylistActivityFavoriteRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playlistId': value['playlistId'],
        'isFavorite': value['isFavorite'],
    };
}

