/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPlaylistActivity
 */
export interface UserPlaylistActivity {
    /**
     * 
     * @type {string}
     * @memberof UserPlaylistActivity
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPlaylistActivity
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPlaylistActivity
     */
    title: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPlaylistActivity
     */
    playlistId: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPlaylistActivity
     */
    playlistThumbnailUrl: string | null;
    /**
     * 
     * @type {Array<Date>}
     * @memberof UserPlaylistActivity
     */
    datesPlayed?: Array<Date> | null;
    /**
     * 
     * @type {Date}
     * @memberof UserPlaylistActivity
     */
    lastPlayed?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof UserPlaylistActivity
     */
    isFavorite?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UserPlaylistActivity
     */
    dateFavorited?: Date | null;
}

/**
 * Check if a given object implements the UserPlaylistActivity interface.
 */
export function instanceOfUserPlaylistActivity(value: object): value is UserPlaylistActivity {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('playlistId' in value) || value['playlistId'] === undefined) return false;
    if (!('playlistThumbnailUrl' in value) || value['playlistThumbnailUrl'] === undefined) return false;
    return true;
}

export function UserPlaylistActivityFromJSON(json: any): UserPlaylistActivity {
    return UserPlaylistActivityFromJSONTyped(json, false);
}

export function UserPlaylistActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPlaylistActivity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'title': json['title'],
        'playlistId': json['playlistId'],
        'playlistThumbnailUrl': json['playlistThumbnailUrl'],
        'datesPlayed': json['datesPlayed'] == null ? undefined : json['datesPlayed'],
        'lastPlayed': json['lastPlayed'] == null ? undefined : (new Date(json['lastPlayed'])),
        'isFavorite': json['isFavorite'] == null ? undefined : json['isFavorite'],
        'dateFavorited': json['dateFavorited'] == null ? undefined : (new Date(json['dateFavorited'])),
    };
}

export function UserPlaylistActivityToJSON(json: any): UserPlaylistActivity {
    return UserPlaylistActivityToJSONTyped(json, false);
}

export function UserPlaylistActivityToJSONTyped(value?: UserPlaylistActivity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'title': value['title'],
        'playlistId': value['playlistId'],
        'playlistThumbnailUrl': value['playlistThumbnailUrl'],
        'datesPlayed': value['datesPlayed'],
        'lastPlayed': value['lastPlayed'] == null ? undefined : ((value['lastPlayed']).toISOString()),
        'isFavorite': value['isFavorite'],
        'dateFavorited': value['dateFavorited'] === null ? null : ((value['dateFavorited'] as any)?.toISOString()),
    };
}

