/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageCode } from './LanguageCode';
import {
    LanguageCodeFromJSON,
    LanguageCodeFromJSONTyped,
    LanguageCodeToJSON,
    LanguageCodeToJSONTyped,
} from './LanguageCode';
import type { Quiz } from './Quiz';
import {
    QuizFromJSON,
    QuizFromJSONTyped,
    QuizToJSON,
    QuizToJSONTyped,
} from './Quiz';

/**
 * 
 * @export
 * @interface UserQuizResult
 */
export interface UserQuizResult {
    /**
     * 
     * @type {string}
     * @memberof UserQuizResult
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserQuizResult
     */
    quizId?: string;
    /**
     * 
     * @type {Quiz}
     * @memberof UserQuizResult
     */
    quiz?: Quiz;
    /**
     * 
     * @type {number}
     * @memberof UserQuizResult
     */
    score?: number;
    /**
     * 
     * @type {LanguageCode}
     * @memberof UserQuizResult
     */
    language?: LanguageCode;
    /**
     * 
     * @type {Date}
     * @memberof UserQuizResult
     */
    dateCompleted?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserQuizResult
     */
    userId?: string;
}



/**
 * Check if a given object implements the UserQuizResult interface.
 */
export function instanceOfUserQuizResult(value: object): value is UserQuizResult {
    return true;
}

export function UserQuizResultFromJSON(json: any): UserQuizResult {
    return UserQuizResultFromJSONTyped(json, false);
}

export function UserQuizResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserQuizResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'quizId': json['quizId'] == null ? undefined : json['quizId'],
        'quiz': json['quiz'] == null ? undefined : QuizFromJSON(json['quiz']),
        'score': json['score'] == null ? undefined : json['score'],
        'language': json['language'] == null ? undefined : LanguageCodeFromJSON(json['language']),
        'dateCompleted': json['dateCompleted'] == null ? undefined : (new Date(json['dateCompleted'])),
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function UserQuizResultToJSON(json: any): UserQuizResult {
    return UserQuizResultToJSONTyped(json, false);
}

export function UserQuizResultToJSONTyped(value?: UserQuizResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'quizId': value['quizId'],
        'quiz': QuizToJSON(value['quiz']),
        'score': value['score'],
        'language': LanguageCodeToJSON(value['language']),
        'dateCompleted': value['dateCompleted'] == null ? undefined : ((value['dateCompleted']).toISOString()),
        'userId': value['userId'],
    };
}

