/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageCode } from './LanguageCode';
import {
    LanguageCodeFromJSON,
    LanguageCodeFromJSONTyped,
    LanguageCodeToJSON,
    LanguageCodeToJSONTyped,
} from './LanguageCode';

/**
 * 
 * @export
 * @interface UserHandwritingResultDto
 */
export interface UserHandwritingResultDto {
    /**
     * 
     * @type {LanguageCode}
     * @memberof UserHandwritingResultDto
     */
    language?: LanguageCode;
    /**
     * 
     * @type {number}
     * @memberof UserHandwritingResultDto
     */
    score?: number;
    /**
     * 
     * @type {string}
     * @memberof UserHandwritingResultDto
     */
    wordTested?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserHandwritingResultDto
     */
    dateCompleted?: Date | null;
}



/**
 * Check if a given object implements the UserHandwritingResultDto interface.
 */
export function instanceOfUserHandwritingResultDto(value: object): value is UserHandwritingResultDto {
    return true;
}

export function UserHandwritingResultDtoFromJSON(json: any): UserHandwritingResultDto {
    return UserHandwritingResultDtoFromJSONTyped(json, false);
}

export function UserHandwritingResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserHandwritingResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'language': json['language'] == null ? undefined : LanguageCodeFromJSON(json['language']),
        'score': json['score'] == null ? undefined : json['score'],
        'wordTested': json['wordTested'] == null ? undefined : json['wordTested'],
        'dateCompleted': json['dateCompleted'] == null ? undefined : (new Date(json['dateCompleted'])),
    };
}

export function UserHandwritingResultDtoToJSON(json: any): UserHandwritingResultDto {
    return UserHandwritingResultDtoToJSONTyped(json, false);
}

export function UserHandwritingResultDtoToJSONTyped(value?: UserHandwritingResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'language': LanguageCodeToJSON(value['language']),
        'score': value['score'],
        'wordTested': value['wordTested'],
        'dateCompleted': value['dateCompleted'] == null ? undefined : ((value['dateCompleted'] as any).toISOString()),
    };
}

