/* tslint:disable */
/* eslint-disable */
/**
 * ChordKTV
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoInfo
 */
export interface VideoInfo {
    /**
     * 
     * @type {string}
     * @memberof VideoInfo
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoInfo
     */
    artist?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoInfo
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoInfo
     */
    duration?: string;
}

/**
 * Check if a given object implements the VideoInfo interface.
 */
export function instanceOfVideoInfo(value: object): value is VideoInfo {
    return true;
}

export function VideoInfoFromJSON(json: any): VideoInfo {
    return VideoInfoFromJSONTyped(json, false);
}

export function VideoInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'artist': json['artist'] == null ? undefined : json['artist'],
        'url': json['url'] == null ? undefined : json['url'],
        'duration': json['duration'] == null ? undefined : json['duration'],
    };
}

export function VideoInfoToJSON(json: any): VideoInfo {
    return VideoInfoToJSONTyped(json, false);
}

export function VideoInfoToJSONTyped(value?: VideoInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'artist': value['artist'],
        'url': value['url'],
        'duration': value['duration'],
    };
}

